sylius_admin_batch_processing:
    resource: |
        alias: sylius.batch_processing
        section: admin
        templates: "@SyliusAdmin\\Crud"
        except: ['show']
        redirect: update
        grid: sylius_admin_batch_processing
        permission: true
        vars:
            all:
                subheader: sylius.ui.batch_processing
                templates:
                    form: "@SyliusAdmin/BatchProcessing/_form.html.twig"
            index:
                icon: share alternate
    type: sylius.resource

sylius_admin_batch_processing_start:
    path: /batch-processings/{id}/start
    methods: [PATCH]
    defaults:
        _controller: sylius.controller.batch_processing.start
