# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_grid:
    grids:
        sylius_shop_product:
            driver:
                name: elastica
                options:
                    class: "%sylius.model.product.class%"
                    repository:
                        method: createQueryWithTaxon
                        arguments: ["expr:service('sylius.repository.taxon').find($taxonId)"]
            filters:
                code:
                    type: nested
                    path:
                        option:
                            type: nested
                name:
                    type: string
            sorting:
                position: asc
            fields:
                createdAt:
                    type: datetime
                    label: sylius.ui.date
                    sortable: ~
                    options:
                        format: m/d/Y
                position: 
                    type: string 
                    sortable: productTaxons.position
            filters:
                search:
                    type: string
                    template: "@SyliusShop/Grid/Filter/string.html.twig"
                    options:
                        fields: [translation.name]
